### ISSUE TITLE
Mod doesn't load correctly. (1.18.2 Forge version)

### ISSUE THREAD

**Issue by Kyralina** [gottsch/gottsch-minecraft-MobDiceAttributes#1]
Error listed in minecraft is: 
`Mob Dice Attributes (mobdiceattribs) has failed to load correctly`
`java.lang.reflect.InvocationTargetException: null`

Version downloaded is "MobDiceAttributes-mc1.18.2-f40.1.0-v1.0.1.jar" from Modrinth.

Full crash report with only this mod loaded is attached.

[crash-2023-02-25_19.27.46-fml.txt](https://github.com/gottsch/gottsch-minecraft-MobDiceAttributes/files/10832892/crash-2023-02-25_19.27.46-fml.txt)

I really like the idea of this mod though, looking forward to getting it working.

**Comment by gottsch** [comment]
You need to install GottschCore as well. It should've prompted you :(
